/**
 * Master venue registry for Long Island rock & metal shows.
 *
 * scraper: 'auto'  → generic engine tries JSON-LD, Bandsintown widget, Songkick, HTML
 * scraper: null    → venue appears on map only (no automated show data)
 *
 * To add a venue: append one entry here. The scraper will try 'auto' by default.
 * Coordinates are approximate — verify with Google Maps if marker placement matters.
 */

export const venues = [
  // ─── Major / Mid-size venues ───────────────────────────────────────────────
  {
    id: '89north',
    name: '89 North',
    location: 'Patchogue, NY',
    coords: [40.7637, -73.0163],
    url: 'https://www.89north.com',
    eventsUrl: 'https://www.89north.com/events',
    facebook: 'https://www.facebook.com/89northmusic',
    instagram: 'https://www.instagram.com/89northmusic',
    scraper: 'auto',
    genre: ['rock', 'metal', 'punk', 'hardcore'],
    active: true,
  },
  {
    id: 'amityville',
    name: 'Amityville Music Hall',
    location: 'Amityville, NY',
    coords: [40.6789, -73.4142],
    url: 'https://www.amityvillemusichall.com',
    eventsUrl: 'https://www.amityvillemusichall.com/events',
    facebook: 'https://www.facebook.com/amityvillemusichall',
    instagram: 'https://www.instagram.com/amityvillemusichall',
    scraper: 'auto',
    genre: ['rock', 'metal', 'punk', 'indie'],
    active: true,
  },
  {
    id: 'paramount',
    name: 'The Paramount',
    location: 'Huntington, NY',
    coords: [40.8682, -73.4257],
    url: 'https://www.paramounthuntington.com',
    eventsUrl: 'https://www.paramounthuntington.com/events',
    facebook: 'https://www.facebook.com/TheParamountNY',
    instagram: 'https://www.instagram.com/theparamountny',
    scraper: 'auto',
    genre: ['rock', 'metal', 'pop', 'comedy'],
    active: true,
  },
  {
    id: 'revolution',
    name: 'Revolution Bar & Music Hall',
    location: 'Amityville, NY',
    coords: [40.6645, -73.4151],
    url: 'https://www.revolutionbar.com',
    eventsUrl: 'https://www.revolutionbar.com/events',
    facebook: 'https://www.facebook.com/RevolutionBarAndMusicHall',
    instagram: 'https://www.instagram.com/revolutionbarmusichall',
    scraper: 'auto',
    genre: ['rock', 'metal', 'punk', 'blues'],
    active: true,
  },
  {
    id: 'mulcahys',
    name: "Mulcahy's",
    location: 'Wantagh, NY',
    coords: [40.6743, -73.5087],
    url: 'https://www.mulcahys.com',
    eventsUrl: 'https://www.mulcahys.com/concerts',
    facebook: 'https://www.facebook.com/MulcahysWantagh',
    instagram: null,
    scraper: 'auto',
    genre: ['rock', 'cover bands', 'tribute'],
    active: true,
  },
  {
    id: 'boulton',
    name: 'Boulton Center',
    location: 'Bay Shore, NY',
    coords: [40.7282, -73.2449],
    url: 'https://www.boultoncenter.org',
    eventsUrl: 'https://www.boultoncenter.org/events',
    facebook: 'https://www.facebook.com/BoultonCenter',
    instagram: null,
    scraper: 'auto',
    genre: ['rock', 'folk', 'blues', 'americana'],
    active: true,
  },
  {
    id: 'thespaceatwestbury',
    name: 'The Space at Westbury',
    location: 'Westbury, NY',
    coords: [40.7548, -73.5766],
    url: 'https://www.thespaceatwestbury.com',
    eventsUrl: 'https://www.thespaceatwestbury.com/events',
    facebook: 'https://www.facebook.com/TheSpaceAtWestbury',
    instagram: 'https://www.instagram.com/thespaceatwestbury',
    scraper: 'auto',
    genre: ['rock', 'metal', 'pop', 'comedy'],
    active: true,
  },
  {
    id: 'ubsarena',
    name: 'UBS Arena',
    location: 'Elmont, NY',
    coords: [40.7040, -73.7259],
    url: 'https://www.ubsarena.com',
    eventsUrl: 'https://www.ubsarena.com/events',
    facebook: 'https://www.facebook.com/UBSArena',
    instagram: 'https://www.instagram.com/ubsarena',
    scraper: 'auto',
    genre: ['rock', 'metal', 'pop', 'sports'],
    active: true,
  },
  {
    id: 'jonesbeach',
    name: 'Northwell Health at Jones Beach Theater',
    location: 'Wantagh, NY',
    coords: [40.5895, -73.5095],
    url: 'https://www.jonesbeachtheater.com',
    eventsUrl: 'https://www.jonesbeachtheater.com/events',
    facebook: 'https://www.facebook.com/JonesBeachTheater',
    instagram: 'https://www.instagram.com/jonesbeachtheater',
    scraper: 'auto',
    genre: ['rock', 'metal', 'pop', 'country'],
    active: true,
  },
  {
    id: 'nassaucoliseum',
    name: 'Nassau Coliseum',
    location: 'Uniondale, NY',
    coords: [40.7228, -73.5932],
    url: 'https://www.nassaucoliseum.com',
    eventsUrl: 'https://www.nassaucoliseum.com/events',
    facebook: 'https://www.facebook.com/NassauColiseum',
    instagram: 'https://www.instagram.com/nassaucoliseum',
    scraper: 'auto',
    genre: ['rock', 'metal', 'pop', 'sports'],
    active: true,
  },
  {
    id: 'ritasoundstage',
    name: "Rita's Soundstage",
    location: 'Bethpage, NY',
    coords: [40.7548, -73.4903],
    url: 'https://www.ritassoundstage.com',
    eventsUrl: 'https://www.ritassoundstage.com/events',
    facebook: 'https://www.facebook.com/ritassoundstage',
    instagram: null,
    scraper: 'auto',
    genre: ['rock', 'cover bands', 'tribute'],
    active: true,
  },
  // ─── Smaller venues & bars ─────────────────────────────────────────────────
  {
    id: 'rudis',
    name: "Rudi's",
    location: 'Patchogue, NY',
    coords: [40.7642, -73.0148],
    url: null,
    eventsUrl: null,
    facebook: 'https://www.facebook.com/rudispatchogue',
    instagram: null,
    scraper: null, // map-only — posts on Facebook
    genre: ['rock', 'cover bands'],
    active: true,
  },
  {
    id: 'canalbar',
    name: 'Canal Bar & Grille',
    location: 'Smithtown, NY',
    coords: [40.8556, -73.2004],
    url: null,
    eventsUrl: null,
    facebook: 'https://www.facebook.com/CanalBarGrille',
    instagram: null,
    scraper: null,
    genre: ['rock', 'cover bands'],
    active: true,
  },
  {
    id: 'steelybeer',
    name: "Steely Beer",
    location: 'Amityville, NY',
    coords: [40.6789, -73.4138],
    url: null,
    eventsUrl: null,
    facebook: 'https://www.facebook.com/steelybeerar',
    instagram: null,
    scraper: null,
    genre: ['rock', 'blues', 'cover bands'],
    active: true,
  },
  {
    id: 'pjsweeney',
    name: "PJ Sweeney's",
    location: 'Bohemia, NY',
    coords: [40.7704, -73.1276],
    url: null,
    eventsUrl: null,
    facebook: 'https://www.facebook.com/PJSweeneys',
    instagram: null,
    scraper: null,
    genre: ['rock', 'cover bands'],
    active: true,
  },
  {
    id: 'finleys',
    name: "Finley's Bar & Grill",
    location: 'Bay Shore, NY',
    coords: [40.7269, -73.2462],
    url: null,
    eventsUrl: null,
    facebook: 'https://www.facebook.com/FinleysBayShore',
    instagram: null,
    scraper: null,
    genre: ['rock', 'cover bands'],
    active: true,
  },
  {
    id: 'napperhuntington',
    name: "Napper Tandy's",
    location: 'Huntington, NY',
    coords: [40.8690, -73.4268],
    url: null,
    eventsUrl: null,
    facebook: 'https://www.facebook.com/NapperTandysHuntington',
    instagram: null,
    scraper: null,
    genre: ['rock', 'cover bands', 'irish'],
    active: true,
  },
  {
    id: 'thebarrelhouse',
    name: 'The Barrel House',
    location: 'Patchogue, NY',
    coords: [40.7648, -73.0155],
    url: null,
    eventsUrl: null,
    facebook: null,
    instagram: null,
    scraper: null,
    genre: ['rock', 'blues'],
    active: true,
  },
  {
    id: 'therepublic',
    name: 'The Republic',
    location: 'Garden City, NY',
    coords: [40.7268, -73.6348],
    url: 'https://www.republicnyc.com',
    eventsUrl: 'https://www.republicnyc.com/events',
    facebook: 'https://www.facebook.com/RepublicNYC',
    instagram: 'https://www.instagram.com/republicnyc',
    scraper: 'auto',
    genre: ['rock', 'metal', 'punk', 'electronic'],
    active: true,
  },
  {
    id: 'louies',
    name: "Louie's Oyster Bar",
    location: 'Port Washington, NY',
    coords: [40.8329, -73.6946],
    url: 'https://www.louiesoysterbar.com',
    eventsUrl: null,
    facebook: 'https://www.facebook.com/louiesoysterbar',
    instagram: null,
    scraper: null,
    genre: ['rock', 'cover bands'],
    active: true,
  },
  {
    id: 'captains',
    name: "Captain Daniel Packer Inne",
    location: 'Mystic, CT',
    coords: [41.3543, -71.9668],
    url: null,
    eventsUrl: null,
    facebook: null,
    instagram: null,
    scraper: null,
    genre: ['rock', 'blues'],
    active: false, // out of area — example of how to disable
  },
  {
    id: 'riptides',
    name: 'Rip Tides',
    location: 'Lindenhurst, NY',
    coords: [40.6859, -73.3773],
    url: null,
    eventsUrl: null,
    facebook: null,
    instagram: null,
    scraper: null,
    genre: ['rock', 'cover bands'],
    active: true,
  },
  {
    id: 'theelbow',
    name: 'The Elbow Room',
    location: 'Patchogue, NY',
    coords: [40.7635, -73.0161],
    url: null,
    eventsUrl: null,
    facebook: null,
    instagram: null,
    scraper: null,
    genre: ['rock', 'blues', 'cover bands'],
    active: true,
  },
  {
    id: 'macsteakhouse',
    name: "Mac's Steakhouse",
    location: 'Huntington, NY',
    coords: [40.8701, -73.4278],
    url: 'https://www.macsteakhouse.com',
    eventsUrl: null,
    facebook: 'https://www.facebook.com/MacsSteakhouse',
    instagram: null,
    scraper: null,
    genre: ['rock', 'blues', 'jazz'],
    active: true,
  },
  {
    id: 'suffolktheater',
    name: 'Suffolk Theater',
    location: 'Riverhead, NY',
    coords: [40.9165, -72.6620],
    url: 'https://www.suffolktheater.com',
    eventsUrl: 'https://www.suffolktheater.com/events',
    facebook: 'https://www.facebook.com/SuffolkTheater',
    instagram: 'https://www.instagram.com/suffolktheater',
    scraper: 'auto',
    genre: ['rock', 'folk', 'blues', 'comedy'],
    active: true,
  },
  {
    id: 'calderone',
    name: 'Calderone Concert Club',
    location: 'Merrick, NY',
    coords: [40.6582, -73.5561],
    url: null,
    eventsUrl: null,
    facebook: null,
    instagram: null,
    scraper: null,
    genre: ['rock', 'metal', 'tribute'],
    active: true,
  },
  {
    id: 'stereogardenli',
    name: 'Stereo Garden',
    location: 'Patchogue, NY',
    coords: [40.7639, -73.0160],
    url: null,
    eventsUrl: null,
    facebook: 'https://www.facebook.com/stereogarden',
    instagram: null,
    scraper: null,
    genre: ['electronic', 'rock'],
    active: true,
  },
]
